stages:
  - install
  - test
  - build
#  - deploy

install_dependencies:
  stage: install
  image: composer:latest
  script:
    - composer install
  artifacts:
    paths:
      - vendor/

test:
  stage: test
  image: php:8.3.13
  before_script:
    - apt-get update && apt-get install -y zip unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  script:
    - ./vendor/bin/phpunit --testdox

build:
  stage: build
  image: php:8.3.13
  script:
    - echo "Building project..."

#deploy:
#  stage: deploy
#  image: alpine:latest
#  only:
#    - main
#  before_script:
#    - apk add --no-cache openssh
#  script:
#    - scp -r ./* user@your_server:/path/to/deployment/
