image: php:8.2-cli

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: user_auth
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_ROOT_PASSWORD: root

cache:
  paths:
    - vendor/
    - ~/.composer/cache

before_script:
  # Install required system dependencies
  - apt-get update && apt-get install -y unzip git
  - php --version

  # Ensure a valid php.ini exists
  - cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

stages:
  - install
  - test
  - build

install_dependencies:
  stage: install
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-progress --ignore-platform-reqs
  artifacts:
    paths:
      - vendor/

run_tests:
  stage: test
  script:
    - echo "Running tests..."
    - docker ps -a
    - php vendor/bin/phpunit --configuration phpunit.xml.dist
  only:
    - main

build:
  stage: build
  script:
    - echo "Building project..."
