image: php:8.2-cli

services:
  - name: mysql:5.7
    alias: mysql

variables:
  MYSQL_HOST: mysql
  MYSQL_DATABASE: user_auth
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_ROOT_PASSWORD: root

cache:
  paths:
    - vendor/
    - ~/.composer/cache

before_script:
  - apt-get update && apt-get install -y unzip git default-mysql-client
  - docker-php-ext-install pdo_mysql
  - php --version
  - |
    echo "Waiting for MySQL to be ready..."
    until mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"; do
      echo "MySQL is not ready yet, waiting...";
      sleep 5;
    done

stages:
  - install
  - test
  - build

install_dependencies:
  stage: install
  script:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-progress --ignore-platform-reqs
  artifacts:
    paths:
      - vendor/

run_tests:
  stage: test
  script:
    - php vendor/bin/phpunit --configuration phpunit.xml.dist
  only:
    - main

build:
  stage: build
  script:
    - echo "Building project..."
